# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtruderCam2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 923)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_interface = QtWidgets.QWidget()
        self.tab_interface.setObjectName("tab_interface")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_interface)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.tab_interface)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.measured_width = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.measured_width.setReadOnly(True)
        self.measured_width.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.measured_width.setDecimals(3)
        self.measured_width.setObjectName("measured_width")
        self.gridLayout_3.addWidget(self.measured_width, 6, 5, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 4, 1, 1)
        self.filament_speed = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.filament_speed.setReadOnly(True)
        self.filament_speed.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.filament_speed.setDecimals(1)
        self.filament_speed.setObjectName("filament_speed")
        self.gridLayout_3.addWidget(self.filament_speed, 3, 5, 1, 2)
        self.text_pipe_in = QtWidgets.QTextBrowser(self.frame_2)
        self.text_pipe_in.setDocumentTitle("")
        self.text_pipe_in.setObjectName("text_pipe_in")
        self.gridLayout_3.addWidget(self.text_pipe_in, 1, 0, 1, 3)
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 3, 4, 1, 1)
        self.gear_speed = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.gear_speed.setReadOnly(True)
        self.gear_speed.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.gear_speed.setDecimals(1)
        self.gear_speed.setObjectName("gear_speed")
        self.gridLayout_3.addWidget(self.gear_speed, 4, 5, 1, 2)
        self.fps = QtWidgets.QDoubleSpinBox(self.frame_2)
        self.fps.setReadOnly(True)
        self.fps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.fps.setDecimals(1)
        self.fps.setMinimum(0.0)
        self.fps.setSingleStep(0.01)
        self.fps.setProperty("value", 15.0)
        self.fps.setObjectName("fps")
        self.gridLayout_3.addWidget(self.fps, 5, 5, 1, 2)
        self.line_4 = QtWidgets.QFrame(self.frame_2)
        self.line_4.setMinimumSize(QtCore.QSize(0, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 2, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 3)
        self.text_pipe_out = QtWidgets.QTextBrowser(self.frame_2)
        self.text_pipe_out.setObjectName("text_pipe_out")
        self.gridLayout_3.addWidget(self.text_pipe_out, 1, 4, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.frame_2)
        self.line_5.setMinimumSize(QtCore.QSize(0, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 2, 4, 1, 3)
        self.record_save = QtWidgets.QPushButton(self.frame_2)
        self.record_save.setEnabled(False)
        self.record_save.setObjectName("record_save")
        self.gridLayout_3.addWidget(self.record_save, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 4, 1, 3)
        self.label_21 = QtWidgets.QLabel(self.frame_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.record_filename = QtWidgets.QLineEdit(self.frame_2)
        self.record_filename.setObjectName("record_filename")
        self.gridLayout_3.addWidget(self.record_filename, 5, 1, 1, 1)
        self.record_start_new = QtWidgets.QPushButton(self.frame_2)
        self.record_start_new.setEnabled(False)
        self.record_start_new.setObjectName("record_start_new")
        self.gridLayout_3.addWidget(self.record_start_new, 4, 0, 1, 1)
        self.record_video = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.record_video.setFont(font)
        self.record_video.setObjectName("record_video")
        self.gridLayout_3.addWidget(self.record_video, 3, 0, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.frame_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 6, 0, 1, 1)
        self.record_state = QtWidgets.QLineEdit(self.frame_2)
        self.record_state.setReadOnly(True)
        self.record_state.setObjectName("record_state")
        self.gridLayout_3.addWidget(self.record_state, 6, 1, 1, 1)
        self.report_results = QtWidgets.QCheckBox(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.report_results.setFont(font)
        self.report_results.setChecked(False)
        self.report_results.setObjectName("report_results")
        self.gridLayout_3.addWidget(self.report_results, 7, 4, 1, 3)
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 6, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 3, 11, 1)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tab_interface, "")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_setup)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.tab_setup)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.img_rotation = QtWidgets.QDoubleSpinBox(self.frame)
        self.img_rotation.setWrapping(True)
        self.img_rotation.setDecimals(3)
        self.img_rotation.setMaximum(359.0)
        self.img_rotation.setObjectName("img_rotation")
        self.gridLayout.addWidget(self.img_rotation, 0, 1, 1, 1)
        self.mat_colour = QtWidgets.QComboBox(self.frame)
        self.mat_colour.setObjectName("mat_colour")
        self.mat_colour.addItem("")
        self.mat_colour.addItem("")
        self.mat_colour.addItem("")
        self.gridLayout.addWidget(self.mat_colour, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.save_config = QtWidgets.QPushButton(self.frame)
        self.save_config.setObjectName("save_config")
        self.gridLayout.addWidget(self.save_config, 9, 0, 1, 6)
        self.mat_type = QtWidgets.QComboBox(self.frame)
        self.mat_type.setObjectName("mat_type")
        self.mat_type.addItem("")
        self.mat_type.addItem("")
        self.gridLayout.addWidget(self.mat_type, 8, 2, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setMinimumSize(QtCore.QSize(0, 10))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 6)
        self.mat_manufacturer = QtWidgets.QLineEdit(self.frame)
        self.mat_manufacturer.setObjectName("mat_manufacturer")
        self.gridLayout.addWidget(self.mat_manufacturer, 8, 3, 1, 1)
        self.mat_date_id = QtWidgets.QLineEdit(self.frame)
        self.mat_date_id.setObjectName("mat_date_id")
        self.gridLayout.addWidget(self.mat_date_id, 8, 5, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 8, 4, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 4, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 4, 0, 1, 1)
        self.gear_roi_x = QtWidgets.QSpinBox(self.frame)
        self.gear_roi_x.setMaximum(640)
        self.gear_roi_x.setObjectName("gear_roi_x")
        self.gridLayout.addWidget(self.gear_roi_x, 4, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 4, 1, 1)
        self.fil_roi_x = QtWidgets.QSpinBox(self.frame)
        self.fil_roi_x.setMaximum(640)
        self.fil_roi_x.setObjectName("fil_roi_x")
        self.gridLayout.addWidget(self.fil_roi_x, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 2, 1, 1)
        self.fil_roi_y = QtWidgets.QSpinBox(self.frame)
        self.fil_roi_y.setMaximum(640)
        self.fil_roi_y.setObjectName("fil_roi_y")
        self.gridLayout.addWidget(self.fil_roi_y, 5, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.w_y2 = QtWidgets.QSpinBox(self.frame)
        self.w_y2.setMaximum(640)
        self.w_y2.setObjectName("w_y2")
        self.gridLayout.addWidget(self.w_y2, 2, 1, 1, 1)
        self.gear_roi_y = QtWidgets.QSpinBox(self.frame)
        self.gear_roi_y.setMaximum(640)
        self.gear_roi_y.setObjectName("gear_roi_y")
        self.gridLayout.addWidget(self.gear_roi_y, 4, 3, 1, 1)
        self.w_vline_left_border = QtWidgets.QSpinBox(self.frame)
        self.w_vline_left_border.setMaximum(640)
        self.w_vline_left_border.setObjectName("w_vline_left_border")
        self.gridLayout.addWidget(self.w_vline_left_border, 2, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 2, 4, 1, 1)
        self.w_vline_right_border = QtWidgets.QSpinBox(self.frame)
        self.w_vline_right_border.setMaximum(640)
        self.w_vline_right_border.setObjectName("w_vline_right_border")
        self.gridLayout.addWidget(self.w_vline_right_border, 2, 5, 1, 1)
        self.gear_roi_size = QtWidgets.QSpinBox(self.frame)
        self.gear_roi_size.setMaximum(640)
        self.gear_roi_size.setObjectName("gear_roi_size")
        self.gridLayout.addWidget(self.gear_roi_size, 4, 5, 1, 1)
        self.fil_roi_size = QtWidgets.QSpinBox(self.frame)
        self.fil_roi_size.setMaximum(640)
        self.fil_roi_size.setObjectName("fil_roi_size")
        self.gridLayout.addWidget(self.fil_roi_size, 5, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.vline_left = QtWidgets.QSpinBox(self.frame)
        self.vline_left.setMaximum(640)
        self.vline_left.setObjectName("vline_left")
        self.gridLayout.addWidget(self.vline_left, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.vline_right = QtWidgets.QSpinBox(self.frame)
        self.vline_right.setMaximum(640)
        self.vline_right.setObjectName("vline_right")
        self.gridLayout.addWidget(self.vline_right, 0, 5, 1, 1)
        self.img_rotation.raise_()
        self.label_3.raise_()
        self.label_13.raise_()
        self.mat_colour.raise_()
        self.save_config.raise_()
        self.mat_type.raise_()
        self.mat_manufacturer.raise_()
        self.mat_date_id.raise_()
        self.label_20.raise_()
        self.line_3.raise_()
        self.label_28.raise_()
        self.gear_roi_x.raise_()
        self.label_29.raise_()
        self.label_8.raise_()
        self.fil_roi_x.raise_()
        self.label_9.raise_()
        self.fil_roi_y.raise_()
        self.label_7.raise_()
        self.w_y2.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.gear_roi_y.raise_()
        self.w_vline_left_border.raise_()
        self.label_26.raise_()
        self.w_vline_right_border.raise_()
        self.gear_roi_size.raise_()
        self.fil_roi_size.raise_()
        self.label_5.raise_()
        self.vline_left.raise_()
        self.label_6.raise_()
        self.vline_right.raise_()
        self.verticalLayout_3.addWidget(self.frame)
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_calibrate = QtWidgets.QWidget()
        self.tab_calibrate.setObjectName("tab_calibrate")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_calibrate)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_4 = QtWidgets.QFrame(self.tab_calibrate)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 1, 1, 1)
        self.calibrate = QtWidgets.QPushButton(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.calibrate.setFont(font)
        self.calibrate.setObjectName("calibrate")
        self.gridLayout_4.addWidget(self.calibrate, 4, 1, 1, 2)
        self.filament_width = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.filament_width.setDecimals(3)
        self.filament_width.setMinimum(1.0)
        self.filament_width.setProperty("value", 2.85)
        self.filament_width.setObjectName("filament_width")
        self.gridLayout_4.addWidget(self.filament_width, 0, 2, 1, 1)
        self.calfactor_inv = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.calfactor_inv.setReadOnly(True)
        self.calfactor_inv.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.calfactor_inv.setDecimals(3)
        self.calfactor_inv.setMinimum(0.001)
        self.calfactor_inv.setObjectName("calfactor_inv")
        self.gridLayout_4.addWidget(self.calfactor_inv, 2, 2, 1, 1)
        self.cal_factor = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.cal_factor.setReadOnly(True)
        self.cal_factor.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cal_factor.setDecimals(4)
        self.cal_factor.setMinimum(0.001)
        self.cal_factor.setSingleStep(0.001)
        self.cal_factor.setObjectName("cal_factor")
        self.gridLayout_4.addWidget(self.cal_factor, 1, 2, 1, 1)
        self.cal_date = QtWidgets.QDateTimeEdit(self.frame_4)
        self.cal_date.setReadOnly(True)
        self.cal_date.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cal_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 1, 19), QtCore.QTime(15, 30, 0)))
        self.cal_date.setObjectName("cal_date")
        self.gridLayout_4.addWidget(self.cal_date, 3, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 2, 1)
        self.gridLayout_5.addWidget(self.frame_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(444, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_calibrate, "")
        self.tab_detection = QtWidgets.QWidget()
        self.tab_detection.setObjectName("tab_detection")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_detection)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_detection)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.width_thresh_inv = QtWidgets.QCheckBox(self.frame_3)
        self.width_thresh_inv.setEnabled(False)
        self.width_thresh_inv.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.width_thresh_inv.setObjectName("width_thresh_inv")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.width_thresh_inv)
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line)
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(505, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 77, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_detection, "")
        self.tab_video = QtWidgets.QWidget()
        self.tab_video.setObjectName("tab_video")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_video)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 1, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.tab_video)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_number = QtWidgets.QSlider(self.frame_5)
        self.frame_number.setEnabled(False)
        self.frame_number.setOrientation(QtCore.Qt.Horizontal)
        self.frame_number.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.frame_number.setObjectName("frame_number")
        self.gridLayout_6.addWidget(self.frame_number, 2, 0, 1, 3)
        self.frame_next = QtWidgets.QPushButton(self.frame_5)
        self.frame_next.setEnabled(False)
        self.frame_next.setObjectName("frame_next")
        self.gridLayout_6.addWidget(self.frame_next, 1, 1, 1, 1)
        self.play_video = QtWidgets.QCheckBox(self.frame_5)
        self.play_video.setEnabled(False)
        self.play_video.setObjectName("play_video")
        self.gridLayout_6.addWidget(self.play_video, 1, 2, 1, 1)
        self.frame_prev = QtWidgets.QPushButton(self.frame_5)
        self.frame_prev.setEnabled(False)
        self.frame_prev.setObjectName("frame_prev")
        self.gridLayout_6.addWidget(self.frame_prev, 1, 0, 1, 1)
        self.load_video = QtWidgets.QPushButton(self.frame_5)
        self.load_video.setEnabled(False)
        self.load_video.setObjectName("load_video")
        self.gridLayout_6.addWidget(self.load_video, 0, 0, 1, 3)
        self.gridLayout_7.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_video, "")
        self.tab_camera = QtWidgets.QWidget()
        self.tab_camera.setObjectName("tab_camera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_camera)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_camera)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_8.addWidget(self.label_23, 0, 0, 1, 1)
        self.cam_model = QtWidgets.QLineEdit(self.groupBox)
        self.cam_model.setReadOnly(True)
        self.cam_model.setObjectName("cam_model")
        self.gridLayout_8.addWidget(self.cam_model, 0, 1, 1, 1)
        self.cam_number = QtWidgets.QSpinBox(self.groupBox)
        self.cam_number.setReadOnly(True)
        self.cam_number.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cam_number.setObjectName("cam_number")
        self.gridLayout_8.addWidget(self.cam_number, 0, 2, 1, 1)
        self.cam_fps = QtWidgets.QSpinBox(self.groupBox)
        self.cam_fps.setReadOnly(True)
        self.cam_fps.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cam_fps.setMinimum(1)
        self.cam_fps.setMaximum(999)
        self.cam_fps.setSingleStep(15)
        self.cam_fps.setProperty("value", 30)
        self.cam_fps.setObjectName("cam_fps")
        self.gridLayout_8.addWidget(self.cam_fps, 0, 4, 1, 1)
        self.cam_table = QtWidgets.QTableWidget(self.groupBox)
        self.cam_table.setObjectName("cam_table")
        self.cam_table.setColumnCount(0)
        self.cam_table.setRowCount(0)
        self.gridLayout_8.addWidget(self.cam_table, 2, 0, 1, 5)
        self.horizontalLayout.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_camera, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.groupBox_video = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_video.sizePolicy().hasHeightForWidth())
        self.groupBox_video.setSizePolicy(sizePolicy)
        self.groupBox_video.setMinimumSize(QtCore.QSize(640, 500))
        self.groupBox_video.setObjectName("groupBox_video")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_video)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.groupBox_video)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.measured_width.setSuffix(_translate("MainWindow", " mm"))
        self.label_16.setText(_translate("MainWindow", "Gear Speed"))
        self.filament_speed.setSuffix(_translate("MainWindow", " mm/s"))
        self.label_17.setText(_translate("MainWindow", "Filament Speed"))
        self.gear_speed.setSuffix(_translate("MainWindow", " mm/s"))
        self.fps.setSuffix(_translate("MainWindow", " 1/s"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Pipe In</span></p></body></html>"))
        self.record_save.setText(_translate("MainWindow", "Save Video"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Process Log</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "Filename"))
        self.record_start_new.setText(_translate("MainWindow", "Start New"))
        self.record_video.setText(_translate("MainWindow", "Record Video (Start, Pause, Stop)"))
        self.label_22.setText(_translate("MainWindow", "Video Recording:"))
        self.record_state.setText(_translate("MainWindow", "Ready"))
        self.report_results.setText(_translate("MainWindow", "Report Results to Pipe"))
        self.label_18.setText(_translate("MainWindow", "FPS"))
        self.label_19.setText(_translate("MainWindow", "Measured Width"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_interface), _translate("MainWindow", "Interface"))
        self.mat_colour.setItemText(0, _translate("MainWindow", "White"))
        self.mat_colour.setItemText(1, _translate("MainWindow", "Clear"))
        self.mat_colour.setItemText(2, _translate("MainWindow", "Black"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Filament </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Image Rotation"))
        self.save_config.setText(_translate("MainWindow", "Save Config"))
        self.mat_type.setItemText(0, _translate("MainWindow", "PLA"))
        self.mat_type.setItemText(1, _translate("MainWindow", "ABS"))
        self.mat_manufacturer.setText(_translate("MainWindow", "Das Filament"))
        self.mat_date_id.setText(_translate("MainWindow", "2016_1"))
        self.label_20.setText(_translate("MainWindow", "Filament Date/ID"))
        self.label_29.setText(_translate("MainWindow", "Gear ROI Y1"))
        self.label_28.setText(_translate("MainWindow", "Gear ROI X1"))
        self.label_10.setText(_translate("MainWindow", "Gear ROI Size"))
        self.label_8.setText(_translate("MainWindow", "Filament Speed ROI X1"))
        self.label_11.setText(_translate("MainWindow", "Filament Speed ROI Size"))
        self.label_9.setText(_translate("MainWindow", "Filament Speed ROI Y1"))
        self.label_12.setText(_translate("MainWindow", "Width Left Border"))
        self.label_7.setText(_translate("MainWindow", "Width Y Pre-End"))
        self.label_26.setText(_translate("MainWindow", "Width Right Border"))
        self.label_5.setText(_translate("MainWindow", "Alignment Line Left"))
        self.label_6.setText(_translate("MainWindow", "Alignment Line Right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("MainWindow", "Setup"))
        self.label_15.setText(_translate("MainWindow", "Filament Width"))
        self.calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.filament_width.setSuffix(_translate("MainWindow", " mm"))
        self.calfactor_inv.setSuffix(_translate("MainWindow", " pxl/mm"))
        self.cal_factor.setSuffix(_translate("MainWindow", " mm/pxl"))
        self.label_4.setText(_translate("MainWindow", "Cal Factor"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_calibrate), _translate("MainWindow", "Calibrate"))
        self.width_thresh_inv.setText(_translate("MainWindow", "Width Thresh Inv"))
        self.label_14.setText(_translate("MainWindow", "Detection settings can go here..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detection), _translate("MainWindow", "Detection"))
        self.frame_next.setText(_translate("MainWindow", "Next"))
        self.play_video.setText(_translate("MainWindow", "Cont. Run"))
        self.frame_prev.setText(_translate("MainWindow", "Prev"))
        self.load_video.setText(_translate("MainWindow", "Load Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_video), _translate("MainWindow", "Load Video"))
        self.groupBox.setTitle(_translate("MainWindow", "Camera Settings"))
        self.label_24.setText(_translate("MainWindow", "Framerate"))
        self.label_23.setText(_translate("MainWindow", "Camera Model"))
        self.cam_fps.setSuffix(_translate("MainWindow", " FPS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_camera), _translate("MainWindow", "Camera"))
        self.groupBox_video.setTitle(_translate("MainWindow", "Video Feed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

